### ISSUE TITLE
Titles of etherCAT lines same as Manage etherCAT line status document

### ISSUE THREAD

**Issue by isotuela** [lsst-ts/ts_tma_tma-documentation_maintenance-documents_ethercat_ethercat-line-diagnostic#3]
It'd be good if the two titles for each of the etherCAT lines were named equally in the different parts of these two docs: 
https://ts-tma.lsst.io/docs/tma_maintenance_ethercat_ethercat-line-diagnostic/EtherCAT-Line-Diagnostic.html https://ts-tma.lsst.io/docs/tma_maintenance_ethercat_manage-ethercat-line-status/Manage-EtherCAT-Line-Status.html#tma-pxi-ethercat-line

Phase Drives aka AXES PXI EtherCAT line? 
AXES PXI/ Phase Drives EtherCAT line?

What do you think? Open to suggestions.

**Comment by julen-garcia** [comment]
i agree, but those were different documents and we understand them easily, so thanks for the review.

I personally like the name -> AXES PXI - Phase Drives - EtherCAT line

What do you think @isotuela ?

**Comment by isotuela** [comment]
Also, as discussed in Slack, it´d be good to change the name of the "EtherCAT Line Diagnose" document to something that reflects that also the recovery/reset/restart of the etherCAT line is also available.

**Comment by julen-garcia** [comment]
done here 6186733a
